name: Auto Deploy on App Changes

on:
  push:
    branches: [main]
    paths:
      - 'app/src/**'  # Only trigger when app code changes
  workflow_dispatch:    # Allow manual trigger

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: demo-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build and push Docker image
      run: |
        cd app
        docker build -t demo-app:latest .
        docker tag demo-app:latest 831926585199.dkr.ecr.eu-west-1.amazonaws.com/demo-app:latest
        docker push 831926585199.dkr.ecr.eu-west-1.amazonaws.com/demo-app:latest
    
    - name: Force ECS deployment
      run: |
        # Get your cluster and service names (adjust these)
        aws ecs update-service --cluster your-cluster-name --service demo-app --force-new-deployment --region eu-west-1